### ISSUE TITLE
PipelineController don't work

### ISSUE THREAD

**Issue by seghier** [fstwn/cockatoo#43]
Hello
I tried PipelineController but didn't work , can you please make a simple version to only detect changes when geometries added or removed without other settings like layers , colors ...etc

**Comment by fstwn** [comment]
Hey, do you still need this? I think you've figured it out yourself (based on what I read in McNeel dsciourse)

**Comment by seghier** [comment]
Yes , thanks
But still have some problems, sometimes don't work properly
