### ISSUE TITLE
Icons Dont Appear After Installation

### ISSUE THREAD

**Issue by theadambt** [fstwn/Cockatoo#44]
![cockatoo error](https://github.com/fstwn/cockatoo/assets/118791910/77de0840-061e-489d-8f85-74aa49525ad3)
I am getting an error where the icons don't appear, see attached.  What have I installed incorrectly?

**Comment by fstwn** [comment]
Hi, unfortunately there are no individual icons (yet). This is all very alpha and development has been on hold since 2021 due to lack of time and other responsibilities. Sorry :-(
